import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { db } from "@/lib/db";
import NavigationDraft from "@/components/navigation/model-tabs";
import NavigationDraftSmall from "@/components/navigation/model-tabs-small";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {

  const arrDrafts = await db.draft.findMany();
  
  return (
      <>
      <div className="md:hidden"><NavigationDraftSmall arrDrafts={arrDrafts}/></div>

      <div className="hidden md:block"><NavigationDraft arrDrafts={arrDrafts}/></div>
      {children}
      </>
  );
}
